language: php
php:
- 7.1
- 7.2
- 7.3
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
- WP_VERSION=latest
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update
install:
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv
  config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh mpdf_test root '' localhost $WP_VERSION
script:
- vendor/bin/phpunit --configuration=phpunit.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml .
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qLDl/8r+QH/sBGhu99gMLScCpYvGx6RC+PtdcLixuj+2OKq5qK+1tvuR8cyugpCS2pd5dF4T8Y7pyF9zi/8JQkMmLYrY5cD3kXaOL7/l2oE3lJ0CcRFHrOVG/tF/FOdA4nzJTPQ8F6Mq0sVm07NcT5NmvSfqx8VlrBFNB0GNUZYoWaeI6yZxNsLEIQQewSdqJIuVVBkbU6nd6fIkpEydeqpf/R46HVPFSD5Tz3mnMXoHgF+ScbGGlRQ+smAj3oF/LVAmwoW3m5Twa+CWwcdXU/xf9aiO2+vWaQ1BhIUiJYMiUyu38SlC3YbBjekYSfX8r5VQff/4Ng8XfugAy201EahYzQRAmRDrFH/45eXBXm/9PP+GtdyJtRNeKYHU1N8M2nJwvRYBOA6+yxTT3kejT4gQZTxCGozvH+HeFLMonrC0u3YxIIUTYorJp+e1uepPmpM/rbwDdZUbnhU0zF49m0WhAPYPeZC0RaRalSyK0UurUTzoJ/TIqsx6J2DMMdmKZ/Ne8xm+DubtxtzHNab4WCg842rl7Y0Dka4ZexOEOlXxHk1SCVgOz3vxLOentRdV9kXRZzdpSX1xHOa/IuuaQj+00YEr60bQ+ewcLFsK7mCvf+VJcBQREj44YPo2y7YKir7qi3nko0ylM4ENa8TVbu2t8aqC3rALqYOZzVa+et4=
  file: pressbooks-mpdf-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: BCcampus/pressbooks-mpdf
    branch: dev
